#docker-compose up
#docker-compose logs app

#version: '3.2'

services:
  app:
    image: '770c95f6b697dce3c8c195a1883c55732f1d4d1f1b69203e2bd5d336fe07f749'
    container_name: cats_docker
    expose:
      - '9200'
    ports:
      - '9200:9200'
    environment:
      - DB_USER=cats
      - DB_PASSWORD=12345
      - DB_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db
  db:
    image: 'postgres'
    container_name: db
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=cats
      - POSTGRES_PASSWORD=12345

